### ISSUE TITLE
MD037 should be ignored on code fence opening line

### ISSUE THREAD

**Issue by nschonni** [DavidAnson/markdownlint#381]
EX:
~~~md
``` yaml $(tag) == 'all-api-versions' /* autogenerated */
# include the azure profile definitions from the standard location
require: $(this-folder)/../../../../profiles/readme.md

# all the input files across all versions
input-file:
  - $(this-folder)/stable/v1.0/AnomalyDetector.json

```
~~~
Outputs `MD037/no-space-in-emphasis Spaces inside emphasis markers [Context: "* autogenerated *"]`, although the metadata comment is an odd thing to have, it's not a place where emphasis styling occurs
