### ISSUE TITLE
MD043: Add an ability to specify exactly one arbitrary heading

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [DavidAnson/markdownlint#475]
Question mark may be used to specify exactly one arbitrary heading in MD043:

```yml
required-headings:
  headings:
    - "?"
    - "## Description"
    - "## Usage"
    - "## Supported environments and examples"
```

It would be useful when the first header is a program name like [here](https://github.com/Console-Utils/fish-configs).
