### ISSUE TITLE
Documentation for "strict" and "stern"

### ISSUE THREAD

**Issue by aguynamedben** [DavidAnson/markdownlint#688]
The `line-length` rule has these settings:
```yml
# MD013/line-length - Line length
MD013:
  # Strict length checking
  strict: false
  # Stern length checking
  stern: false
```

Is there any documentation for how "strict" and "stern" affect the behavior of the linter? Do they produce warnings, but still a `0` return code? What's the difference between "strict" and "stern"?
