### ISSUE TITLE
MD052: Add option to apply to shortcut reference links too 

### ISSUE THREAD

**Issue by waldyrious** [DavidAnson/markdownlint#915]
Currently, [MD052](https://github.com/DavidAnson/markdownlint/blob/v0.29.0/doc/md052.md) has the following caveat:

> "Shortcut" syntax is ambiguous and a missing label will not generate an error. For example, `[shortcut]` could be a shortcut link or the text "shortcut" in brackets.

I'd like to have an option (defaulting to false in light of the caveat above) to make MD052 also apply to shortcut-syntax reference links, so that I could configure it like this:

```yaml
# MD052/reference-links-images
MD052:
  # Also validate reference links using shortcut syntax
  shortcut_links: true
```

_(This issue stems from a discussion that started [here](https://github.com/DavidAnson/markdownlint/issues/456#issuecomment-1645448773).)_
